name: "Mainflow"

on:
  # push:
  #   branches:
  #     - "master"
  workflow_dispatch:
    inputs:
      cname:
        type: string
        required: true
        description: "Inform CNAME name"
  #     cvalue:
  #       type: string
  #       required: true
  #       description: "Inform CNAME value"

env:
  TF_VAR_CNAME_NAME: "${{ github.event.inputs.cvalue }}"
  TF_VAR_ANOTHER_VAR: HEY THERE UP HEREeee
  TF_CLOUD_ORGANIZATION: "bennun-labs"
  TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"
  TF_WORKSPACE: "teste-envs"
  #ENV_FROM_INPUT: "${{ github.event.inputs.cvalue }}"
  CONFIG_DIRECTORY: "./"

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform format
        id: fmt
        run: terraform fmt -check
      
      - name: Terraform init
        id: init
        run: terraform init

      - name: Terraform validate
        id: validate
        run: terraform validate -no-color
      
      - name: Terraform plan
        id: plan
        run: terraform plan -input=false
        continue-on-error: true
      
      - name: Terraform apply
        run: terraform apply -auto-approve -input=false