name: "Mainflow"

on:
  workflow_dispatch:
    inputs:
      cname:
        type: string
        required: true
        description: "Inform CNAME name"
      cvalue:
        type: string
        required: true
        description: "Inform CNAME value"

env:
  TF_VAR_CNAME_NAME: "Eitchaaa"
  ENV_FROM_INPUT: "${{ github.event.inputs.cvalue }}"

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Use input values
        run: |
          echo "Input CNAME_NAME ${{ github.event.inputs.cname }}"
          echo "Input CNAME_VALUE ${{ github.event.inputs.cvalue }}"
          echo "Env: $TF_VAR_CNAME_NAME"
          echo "Env from input: $ENV_FROM_INPUT"