name: "Mainflow"

on:
  workflow_dispatch:
    inputs:
      cname:
        type: string
        required: true
        description: "Inform CNAME name"
      cvalue:
        type: string
        required: true
        description: "Inform CNAME value"

env:
  TF_CLOUD_ORGANIZATION: ${{env.TF_ORGANIZATION}}
  TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"
  TF_WORKSPACE: ${{env.TF_WORKSPACE}}
  CONFIG_DIRECTORY: "./"

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest   
    steps:
      - name: checkout
        uses: actions/checkout@v3
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.3 
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform init
        id: init
        run: terraform init

      - name: Terraform validate
        id: validate
        run: terraform validate
      
      - name: Terraform plan
        id: plan
        run: 
          export TF_VAR_CNAME_NAME=${{ github.event.inputs.cname }}
          export TF_VAR_CNAME_VALUE=${{ github.event.inputs.cvalue }}
          terraform plan
        continue-on-error: true
      
      - name: Terraform apply
        run: |
          export TF_VAR_CNAME_NAME=${{ github.event.inputs.cname }}
          export TF_VAR_CNAME_VALUE=${{ github.event.inputs.cvalue }}
          echo "heyho! vamos GUS!"
          terraform apply -auto-approve -input=false